In [5]:
import numpy as np
import torch

In [6]:
import gym

In [7]:
env = gym.make("InvertedPendulum-v2")

In [8]:
env.reset()

array([ 0.00474255, -0.00800103,  0.00262595,  0.00183093])

In [9]:
a = env.action_space.sample()

In [10]:
state, _, _, _ = env.step(a) 
state

array([ 0.00057321,  0.00196841, -0.21045305,  0.49137361])

In [11]:
action = env.action_space.sample()
next_state, reward, done, _ = env.step(action)
action

array([-1.2743204], dtype=float32)

In [12]:
state_dim = env.observation_space.shape[0]
action_dim = env.action_space.shape[0] 
action_low = env.action_space.low[0]
action_high = env.action_space.high[0]
state_low = env.observation_space.low
state_high = env.observation_space.high

max_action = float(action_high)
print(f"state low, high: {state_low, state_high}  action low, high: {action_low, action_high}")

state low, high: (array([-inf, -inf, -inf, -inf]), array([inf, inf, inf, inf]))  action low, high: (-3.0, 3.0)


In [13]:
def normalize_action(x):
    return (x-action_low)/(action_high-action_low)

# TODO find a way to scale this
def normalize_state(s):
    return s
def normalize_reward(r):
    return np.array([r/20.0])


In [14]:
# data = torch.Tensor(np.concatenate((state, action, next_state, np.array([reward]), np.array([done]))))     
data = np.concatenate((normalize_state(state), normalize_action(action), normalize_state(next_state), normalize_reward(reward), np.array([done])))
# normalize_state(state)
data

array([ 5.73214638e-04,  1.96840518e-03, -2.10453050e-01,  4.91373608e-01,
        2.87613273e-01, -1.71270390e-02,  4.29288950e-02, -6.73455063e-01,
        1.54879112e+00,  5.00000000e-02,  0.00000000e+00])

In [15]:
datas = [data, data, data]
datas

[array([ 5.73214638e-04,  1.96840518e-03, -2.10453050e-01,  4.91373608e-01,
         2.87613273e-01, -1.71270390e-02,  4.29288950e-02, -6.73455063e-01,
         1.54879112e+00,  5.00000000e-02,  0.00000000e+00]),
 array([ 5.73214638e-04,  1.96840518e-03, -2.10453050e-01,  4.91373608e-01,
         2.87613273e-01, -1.71270390e-02,  4.29288950e-02, -6.73455063e-01,
         1.54879112e+00,  5.00000000e-02,  0.00000000e+00]),
 array([ 5.73214638e-04,  1.96840518e-03, -2.10453050e-01,  4.91373608e-01,
         2.87613273e-01, -1.71270390e-02,  4.29288950e-02, -6.73455063e-01,
         1.54879112e+00,  5.00000000e-02,  0.00000000e+00])]

In [16]:
d = np.array([i for i in datas])

In [17]:
d[0]

array([ 5.73214638e-04,  1.96840518e-03, -2.10453050e-01,  4.91373608e-01,
        2.87613273e-01, -1.71270390e-02,  4.29288950e-02, -6.73455063e-01,
        1.54879112e+00,  5.00000000e-02,  0.00000000e+00])

In [18]:
# Save data
def save_data():
    res = []
    for da in datas:
        res.append(da)
    print(res)
    np.save("env.npy", res)

    

In [19]:
save_data()

[array([ 5.73214638e-04,  1.96840518e-03, -2.10453050e-01,  4.91373608e-01,
        2.87613273e-01, -1.71270390e-02,  4.29288950e-02, -6.73455063e-01,
        1.54879112e+00,  5.00000000e-02,  0.00000000e+00]), array([ 5.73214638e-04,  1.96840518e-03, -2.10453050e-01,  4.91373608e-01,
        2.87613273e-01, -1.71270390e-02,  4.29288950e-02, -6.73455063e-01,
        1.54879112e+00,  5.00000000e-02,  0.00000000e+00]), array([ 5.73214638e-04,  1.96840518e-03, -2.10453050e-01,  4.91373608e-01,
        2.87613273e-01, -1.71270390e-02,  4.29288950e-02, -6.73455063e-01,
        1.54879112e+00,  5.00000000e-02,  0.00000000e+00])]


In [20]:
saved = np.load("env.npy", allow_pickle=True)
saved

array([[ 5.73214638e-04,  1.96840518e-03, -2.10453050e-01,
         4.91373608e-01,  2.87613273e-01, -1.71270390e-02,
         4.29288950e-02, -6.73455063e-01,  1.54879112e+00,
         5.00000000e-02,  0.00000000e+00],
       [ 5.73214638e-04,  1.96840518e-03, -2.10453050e-01,
         4.91373608e-01,  2.87613273e-01, -1.71270390e-02,
         4.29288950e-02, -6.73455063e-01,  1.54879112e+00,
         5.00000000e-02,  0.00000000e+00],
       [ 5.73214638e-04,  1.96840518e-03, -2.10453050e-01,
         4.91373608e-01,  2.87613273e-01, -1.71270390e-02,
         4.29288950e-02, -6.73455063e-01,  1.54879112e+00,
         5.00000000e-02,  0.00000000e+00]])

In [21]:
x = torch.Tensor(saved)

In [22]:
x

tensor([[ 5.7321e-04,  1.9684e-03, -2.1045e-01,  4.9137e-01,  2.8761e-01,
         -1.7127e-02,  4.2929e-02, -6.7346e-01,  1.5488e+00,  5.0000e-02,
          0.0000e+00],
        [ 5.7321e-04,  1.9684e-03, -2.1045e-01,  4.9137e-01,  2.8761e-01,
         -1.7127e-02,  4.2929e-02, -6.7346e-01,  1.5488e+00,  5.0000e-02,
          0.0000e+00],
        [ 5.7321e-04,  1.9684e-03, -2.1045e-01,  4.9137e-01,  2.8761e-01,
         -1.7127e-02,  4.2929e-02, -6.7346e-01,  1.5488e+00,  5.0000e-02,
          0.0000e+00]])

In [23]:
x[0]

tensor([ 5.7321e-04,  1.9684e-03, -2.1045e-01,  4.9137e-01,  2.8761e-01,
        -1.7127e-02,  4.2929e-02, -6.7346e-01,  1.5488e+00,  5.0000e-02,
         0.0000e+00])

In [24]:
env.env.state

AttributeError: 'InvertedPendulumEnv' object has no attribute 'state'

In [25]:
states = np.load('states.npy')

In [30]:
states[56]

array([ 0.08832874, -0.19864326,  0.77022603, -1.8135099 ])

In [28]:
maxes = [0, 0, 0, 0]

In [32]:
for m in range(4):
    for s in states:
        if s[m] > maxes[m]:
            maxes[m] = s[m]
maxes

[1.0179514302477088, 0.42726173641488, 3.4399882898950325, 6.858454176498342]

In [33]:
mins = [100, 100, 100, 100]

In [35]:
for m in range(4):
    for s in states:
        if s[m] < mins[m]:
            mins[m] = s[m]
mins

[-1.0325530575468773,
 -0.43610137064146526,
 -3.385616455699197,
 -7.267725878409552]