In [37]:
import numpy as np
import torch
import gym
from tqdm import tqdm

In [38]:
env = gym.make("InvertedPendulum-v2")
env.reset()

array([-0.00842917, -0.0011419 , -0.0084329 ,  0.00360313])

In [39]:
AMOUNT = 100000
FILE_NAME = "testing.npy"

In [40]:
state_dim = env.observation_space.shape[0]
action_dim = env.action_space.shape[0] 
action_low = env.action_space.low[0]
action_high = env.action_space.high[0]
state_low = -10
state_high = 10

# print(state_low)
def normalize_action(x):
    return (x-action_low)/(action_high-action_low)
# TODO find a way to scale this
def normalize_state(s):
    res = []
    for i in s:
        res.append((i-state_low)/(state_high-state_low))
    return res
def normalize_reward(r):
    return np.array([r/20.0])

In [41]:
raw = []
a = env.action_space.sample()
old_state, _, _, _ = env.step(a) 
dones = 0
for i in tqdm(range(AMOUNT)):
    a = env.action_space.sample()
    s, r, d, _ = env.step(a)
    raw.append(np.concatenate((normalize_state(old_state), normalize_action(a), normalize_state(s), normalize_reward(r), np.array([d]))))
    if d:
        dones += 1
        old_state = env.reset()
print(dones)
    
               
               

    

100%|██████████| 100000/100000 [00:12<00:00, 7801.49it/s]

17516


In [42]:
raw[345]

array([0.50010842, 0.49990523, 0.50048546, 0.49955425, 0.67319506,
       0.50809504, 0.48214664, 0.60620252, 0.26194582, 0.05      ,
       1.        ])

In [43]:
np.save(FILE_NAME, raw)

In [44]:
saved = np.load(FILE_NAME, allow_pickle=True)

In [45]:
saved[345]

array([0.50010842, 0.49990523, 0.50048546, 0.49955425, 0.67319506,
       0.50809504, 0.48214664, 0.60620252, 0.26194582, 0.05      ,
       1.        ])

In [46]:
x = torch.Tensor(saved)

In [47]:
x[345]

tensor([0.5001, 0.4999, 0.5005, 0.4996, 0.6732, 0.5081, 0.4821, 0.6062, 0.2619,
        0.0500, 1.0000])

In [48]:
x = "absadcds"
x[2:]
# x[:2]

'sadcds'

In [49]:
for s in tqdm(saved):
    for a in s:
#         print(s)
        if a > 1 or a < 0:
            print('ALARM')

100%|██████████| 100000/100000 [00:00<00:00, 117574.32it/s]
