In [1]:
import numpy as np
import torch
import gym
from tqdm import tqdm

In [2]:
env = gym.make("InvertedPendulum-v2")
env.reset()

array([-0.00149742, -0.00667878,  0.00242225,  0.00700536])

In [3]:
AMOUNT = 100000
FILE_NAME = f"testing.npy"

In [4]:
state_dim = env.observation_space.shape[0]
action_dim = env.action_space.shape[0] 
action_low = env.action_space.low[0]
action_high = env.action_space.high[0]
state_low = -10.0
state_high = 10.0
print(action_dim)
# print(state_low)
def normalize_action(x):
    return (x-action_low)/(action_high-action_low)
# TODO find a way to scale this
def normalize_state(s):
    res = []
    for i in s:
        res.append((i-state_low)/(state_high-state_low))
    return res
def normalize_reward(r):
    return np.array([r/20.0])

1


In [5]:
raw = []
a = env.action_space.sample()
old_state, _, _, _ = env.step(a) 
dones = 0
for i in tqdm(range(AMOUNT)):
    a = env.action_space.sample()
    s, r, d, _ = env.step(a)
    raw.append(np.concatenate((normalize_state(old_state), normalize_action(a), normalize_state(s), normalize_reward(r), [d])))
    old_state = s
    if d:
        dones += 1
        old_state = env.reset()
print(dones)
    
               
               

    

100%|██████████| 100000/100000 [00:12<00:00, 7731.87it/s]

17609


In [6]:
raw[345]

array([0.50037715, 0.49890415, 0.51859191, 0.45712375, 0.78009874,
       0.50173244, 0.49578274, 0.54909031, 0.38730875, 0.05      ,
       0.        ])

In [7]:
np.save(FILE_NAME, raw)

In [8]:
saved = np.load(FILE_NAME, allow_pickle=True)

In [17]:
saved[402]

array([0.50093858, 0.49858056, 0.5276213 , 0.43750722, 0.12525876,
       0.50121063, 0.49807053, 0.48616404, 0.53541019, 0.05      ,
       0.        ])

In [10]:
x = torch.Tensor(saved)

In [11]:
x[345]

tensor([0.5004, 0.4989, 0.5186, 0.4571, 0.7801, 0.5017, 0.4958, 0.5491, 0.3873,
        0.0500, 0.0000])

In [12]:
x = "absadcds"
x[2:]
# x[:2]

'sadcds'

In [13]:
for s in tqdm(saved):
    for a in s:
#         print(s)
        if a > 1 or a < 0:
            print('ALARM')

100%|██████████| 100000/100000 [00:00<00:00, 112312.90it/s]


In [14]:
a = [12]

In [15]:
np.save("./test/a", a)