In [1]:
import numpy as np
import torch
import gym
from tqdm import tqdm

In [2]:
env = gym.make("InvertedPendulum-v2")
env.reset()

array([ 0.00141413, -0.0011006 ,  0.00491055, -0.00380654])

In [3]:
AMOUNT = 100000
DONE_HACK = 2
FILE_NAME = f"testing{DONE_HACK}.npy"

In [4]:
state_dim = env.observation_space.shape[0]
action_dim = env.action_space.shape[0] 
action_low = env.action_space.low[0]
action_high = env.action_space.high[0]
state_low = -10
state_high = 10
print(action_dim)
# print(state_low)
def normalize_action(x):
    return (x-action_low)/(action_high-action_low)
# TODO find a way to scale this
def normalize_state(s):
    res = []
    for i in s:
        res.append((i-state_low)/(state_high-state_low))
    return res
def normalize_reward(r):
    return np.array([r/20.0])

1


In [5]:
raw = []
a = env.action_space.sample()
old_state, _, _, _ = env.step(a) 
dones = 0
for i in tqdm(range(AMOUNT)):
    a = env.action_space.sample()
    s, r, d, _ = env.step(a)
    raw.append(np.concatenate((normalize_state(old_state), normalize_action(a), normalize_state(s), normalize_reward(r), [d for i in range(DONE_HACK)])))
    if d:
        dones += 1
        old_state = env.reset()
print(dones)
    
               
               

    

100%|██████████| 100000/100000 [00:13<00:00, 7304.73it/s]

17477


In [6]:
raw[345]

array([0.49977055, 0.49999578, 0.49998657, 0.49951733, 0.684829  ,
       0.50241351, 0.49674004, 0.5316987 , 0.44357807, 0.05      ,
       0.        , 0.        ])

In [7]:
np.save(FILE_NAME, raw)

In [8]:
saved = np.load(FILE_NAME, allow_pickle=True)

In [9]:
saved[345]

array([0.49977055, 0.49999578, 0.49998657, 0.49951733, 0.684829  ,
       0.50241351, 0.49674004, 0.5316987 , 0.44357807, 0.05      ,
       0.        , 0.        ])

In [10]:
x = torch.Tensor(saved)

In [11]:
x[345]

tensor([0.4998, 0.5000, 0.5000, 0.4995, 0.6848, 0.5024, 0.4967, 0.5317, 0.4436,
        0.0500, 0.0000, 0.0000])

In [12]:
x = "absadcds"
x[2:]
# x[:2]

'sadcds'

In [13]:
for s in tqdm(saved):
    for a in s:
#         print(s)
        if a > 1 or a < 0:
            print('ALARM')

100%|██████████| 100000/100000 [00:00<00:00, 113967.23it/s]


In [14]:
a = [12]

In [15]:
np.save("./test/a", a)